server:
  port: 8060

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/restaurant/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/